### ISSUE TITLE
Ledger error APDU_CODE_CLA_NOT_SUPPORTED

### ISSUE THREAD

**Issue by danbryan** [Zondax/ledger-rs#101]
Hey all, i was trying to use my ledger with a tool called [tmkms](https://github.com/iqlusioninc/tmkms).  You can see my original issue here.
[tmkms/issues/554](https://github.com/iqlusioninc/tmkms/issues/554)

Any ideas on whats happening, or what I could try to do to make this work?

➜ ~ cargo version
cargo 1.61.0

➜ ~ cargo install tmkms --features=ledger

➜ ~ tmkms init .

➜ ~ cat tmkms.toml
[[providers.ledgertm]]
chain_ids = ["theta-testnet-001"]

[[validator]]
chain_id = "theta-testnet-001"
addr = "tcp://localhost:26658"
secret_key = "/home/socket/secrets/kms-identity.key"
protocol_version = "legacy"
reconnect = true

➜ ~ RUST_BACKTRACE=1 tmkms start
2022-06-11T17:51:30.922089Z INFO tmkms::commands::start: tmkms 0.12.0 starting up...
The application panicked (crashed).
Message: called Result::unwrap() on an Err value: Ledger(Apdu("[APDU_CODE_CLA_NOT_SUPPORTED] Class not supported"))
Location: /home/socket/.cargo/registry/src/github.com-1ecc6299db9ec823/tmkms-0.12.0/src/keyring/providers/ledgertm/signer.rs:40

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
⋮ 7 frames hidden ⋮
8: tmkms::keyring::providers::ledgertm::signer::<impl core::convert::From<&tmkms::keyring::providers::ledgertm::signer::Ed25519LedgerTmAppSigner> for ed25519_dalek::public::PublicKey>::from::h1c5ee8d3514861ef
at :
9: tmkms::keyring::providers::ledgertm::init::h9ecd220b46c540f2
at :
10: tmkms::chain::load_config::h6b1d89976d3aa046
at :
11: <tmkms::commands::start::StartCommand as abscissa_core::runnable::Runnable>::run::hb259537534e809b5
at :
12: abscissa_core::application::Application::run::ha0bf292f92c39aa2
at :
13: abscissa_core::application:boot:h15f1bdd67d42ee2e
at :
14: tmkms::main::h7c4819f94ac414a4
at :
15: std::sys_common::backtrace::__rust_begin_short_backtrace::h0ab56b7fd3500f73
at :
16: std::rt::lang_start::{{closure}}::h869f3a5e4f261876
at :
17: core::ops::function::impls::<impl core::ops::function::FnOnce for &F>::call_once::hff1d360addf0e0a5
at /rustc/1.61.0/library/core/src/ops/function.rs:259
18: std::panicking::try::do_call::haaf1332f62982d76
at /rustc/1.61.0/library/std/src/panicking.rs:492
19: std::panicking::try::hb1a5ffffc51ce834
at /rustc/1.61.0/library/std/src/panicking.rs:456
20: std::panic::catch_unwind::h8b3ba16b791f0a1a
at /rustc/1.61.0/library/std/src/panic.rs:137
21: std::rt::lang_start_internal::{{closure}}::hc3bf7d68bdc46579
at /rustc/1.61.0/library/std/src/rt.rs:128
22: std::panicking::try::do_call::hb9549501a638587d
at /rustc/1.61.0/library/std/src/panicking.rs:492
23: std::panicking::try::h56ce4741a577b244
at /rustc/1.61.0/library/std/src/panicking.rs:456
24: std::panic::catch_unwind::he844618d24ada429
at /rustc/1.61.0/library/std/src/panic.rs:137
25: std::rt::lang_start_internal::h63ec520e87e83a8d
at /rustc/1.61.0/library/std/src/rt.rs:128
26: main
at :
27: __libc_start_main
at :
28: _start
at /build/glibc/src/glibc/csu/../sysdeps/x86_64/start.S:115

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Run with RUST_BACKTRACE=full to include source snippets.

:link: [zboto Link](https://app.clickup.com/t/2kp8zg1)

**Comment by jleni** [comment]
You are trying to use this with the incorrect app. This was designed to work with an app that completely matches that CLA, the tendermint app.

**Comment by danbryan** [comment]
Can you ellaborate a bit more? My understanding is ledger is compatible with tmkms.  I am using the "cosmos" application (which was developed by tendermint. Is this different from the tendermint application you mentioned?  Originally i posted my issue in the tmkms github https://github.com/iqlusioninc/tmkms/issues/554  and they indicated i should ask here.  I would love a more detailed response if you can because right now i am at a loss for what i can do to resolve this issue of mine.

**Comment by becominginsane** [comment]
The app that TMKMS is looking for is the tendermint-validator app which is not the cosmos app. The error you encountered can happen when the app open on the ledger is different from the expected one, like in your case. 
Each app has a code that they respond to, in this case cosmos responds to 0x55 and the tendermint-validator app responds to 0x56.

**Comment by danbryan** [comment]
So it sounds like your saying that tmkms is looking for this
https://github.com/tendermint/ledger-validator-app

not this
https://github.com/cosmos/ledger-cosmos

Is this right?  Looks to me like ledger-validator-app hasn't been touched in 3 years, and all development moved to  https://github.com/cosmos/ledger-cosmos.   (which im guessing is the same thing that i installed via ledger live when i installed the cosmos app).  I'm still at  a loss on what exactly i need to do to use tmkms with my ledger nano x.  Do i need to build this  old ledger-validator-app and install it on a ledger device?

**Comment by becominginsane** [comment]
We are not in charge of telling you how to retrieve the app you a looking for, I suggest you ask the TMKMS team where to retrieve the app, which is probably gonna be in the ledger live store with a specific provider id. 
If you have more questions I'd also suggest you reach out to ledger on their discord, but the repo you linked appears to be right, but unless specifically stated otherwise officially, you shouldn't build the app yourself and sideload it on your own, but rather get it from the store.

**Comment by danbryan** [comment]
Thanks, ill bring it back to https://github.com/iqlusioninc/tmkms/issues/554
