### ISSUE TITLE
[TransportNativeHID] Mark all const in hidapi as pub

### ISSUE THREAD

**Issue by 0xmigo** [Zondax/ledger-rs#108]
Hi team, I wonder if we can update all of the const in TransportNativeHID to be public? especially the ledger vendor id and channel.

Thanks!

:link: [zboto Link](https://app.clickup.com/t/8677yttew)

**Comment by jleni** [comment]
If this is still relevant, would you be happy to send a PR? We can gladly review & merge your changes.
