### ISSUE TITLE
Don't expose  `length` in the ApduCommand struct 

### ISSUE THREAD

**Issue by prestwich** [Zondax/ledger-rs#12]
the `length` byte in a serialized APDU must be the length of the following data. Exposing it in the struct wastes a byte and allows the user to accidentally make invalid APDU's. Consider the following:

```
// Bitcoin app APDU for retrieiving pubkey information w/ native segwit address
let mut apdu = ApduCommand { 
    cla: 0xe0,
    ins: 0x7a,
    p1: 0x00,
    p2: 0x02,
    length: 0x5,
    data: vec![4u8; 5] // represents derivation "m/67372036"
};

// Produces a valid APDU
apdu.serialize(); 

// represents derivation "m/134744072/134744072"
apdu.data = vec![8u8; 9];

// No error, but now produces an invalid serialized APDU, because apdu.length is still 5 instead of 9
apdu.serialize(); 
```

Instead, the `length` should probably be implicit, and serialize should call `self.data.len()` to produce that byte

**Comment by jleni** [comment]
yes, it makes completely sense! Easy to improve.
We are actually reworking this repo at the moment. We will take this into account.

**Comment by prestwich** [comment]
As a side note, if you specify the APDU response length field, you can use a fixed-length buffer for the `APDUAnswer`. This would remove a significant barrier to to `no_std` support
