### ISSUE TITLE
Unexpected output when using more than one instance

### ISSUE THREAD

**Issue by jmininger** [Zondax/ledger-rs#30]
I imagine that TransportNativeHID is meant to be used as a singleton, or else errors of the sort below will happen. Perhaps the solution is simply preventing multiple instances? 
```rust

use ledger_apdu::APDUCommand;
use ledger::{ TransportNativeHID, LedgerError};

fn app_version() -> APDUCommand {
    APDUCommand {
        cla: 0x80,
        ins: 0x00,
        p1: 0x00,
        p2: 0x00,
        data: Vec::new(),
    }
}

fn app_git_hash() -> APDUCommand {
    APDUCommand {
        cla: 0x80,
        ins: 0x09,
        p1: 0x00,
        p2: 0x00,
        data: Vec::new(),
    }
}

fn do_action() -> Result<(), LedgerError> {
   let ledger_instance_one = TransportNativeHID::new()?; 
   let ledger_instance_two = TransportNativeHID::new()?; 
   let apdu1 = app_version();
   let apdu2 = app_git_hash();
   let res1 = ledger_instance_one.exchange(&apdu1)?;
   let res2 = ledger_instance_two.exchange(&apdu1)?;
   let res3 = ledger_instance_one.exchange(&apdu2)?;
   let res4 = ledger_instance_two.exchange(&apdu2)?;
   println!("R1: {:?}", res1);
   println!("R2: {:?}", res2);
   println!("R3: {:?}", res3);
   println!("R4: {:?}", res4);
   return Ok(());
}

fn main() {
 if let Err(e) = do_action() {
	println!("Failed: {}", e);
 } else { 
    println!("Done"); 
 }
}
```

Expected:
```
R1: APDUAnswer { data: [0, 1, 0], retcode: 36864 }
R2: APDUAnswer { data: [0, 1, 0], retcode: 36864 }
R3: APDUAnswer { data: [84, 69, 83, 84, 42, 0], retcode: 36864 }
R4: APDUAnswer { data: [84, 69, 83, 84, 42, 0], retcode: 36864 }
Done
```

Actual:
```
R1: APDUAnswer { data: [0, 1, 0], retcode: 36864 }
R2: APDUAnswer { data: [0, 1, 0], retcode: 36864 }
R3: APDUAnswer { data: [0, 1, 0], retcode: 36864 }
R4: APDUAnswer { data: [0, 1, 0], retcode: 36864 }
Done
```

:link: [zboto Link](https://app.clickup.com/t/2karmrf)

**Comment by jleni** [comment]
While we didn't have this use case in mind, but it should be easy to fix.
The problem you are seeing is because when you do `::new()` we take the first device we can find.

https://github.com/Zondax/ledger-rs/blob/e24166b802e562d814f7eddd15b49b79f634a5cf/ledger-transport-hid/src/lib.rs#L149

if extend the API to identify different devices, I would expect this to work without problem.

This is where the device enumeration and selection happens:
https://github.com/Zondax/ledger-rs/blob/e24166b802e562d814f7eddd15b49b79f634a5cf/ledger-transport-hid/src/lib.rs#L122-L142

If you have the time, it would be really nice if you can submit a PR
Otherwise, we might be able to this in the following weeks, but unfortunately, it is low priority for us right now.

**Comment by jmininger** [comment]
Hi @jleni thank you for your prompt reply! Yes, at the very least i will make an effort to get a PR up in the next week to prevent non-singleton use case for the same device. For multi-ledger support it seems to me that the fix might not be just so trivial as to allow the iterator to continue after the first device... There would still need to be a way of tracking which of the paths we have given out (so as not to use them again). If you do this however, you would also want to add some sort of heartbeat check so as to allow the "releasing" of the HID_Device resource if, say, it gets unplugged. I will try and figure out the best way to do this.

My other question: Do you happen to know why this issue is occurring at the HID level? The code runs synchronously. It appears to be a buffer type error of some kind, but i can't imagine why clearing the buffer after a read (or before one) would not be the default behavior. I suspect there is more at play, but i have not had the time to read the HIDAPI src. Perhaps you know?

**Comment by becominginsane** [comment]
Hi @jmininger, 
I've investigated your issue and added the necessary functions to open multiple instances or even multiple devices, which is part of commit https://github.com/Zondax/ledger-rs/pull/82/commits/35c4fb5df26ae16bcf445f722392cd751456b0d0.

A word of warning: opening multiple instances of the ledger device leads to the ledger locking up after the first instance is closed, see https://github.com/ruabmbua/hidapi-rs/issues/81.
