### ISSUE TITLE
Build issue in v0.7.x due to upstream packages

### ISSUE THREAD

**Issue by shufps** [Zondax/ledger-rs#49]
Solution for this probably is:

quote:`I was able to get past this by forcing protobuf and protoc-rust to version 2.17.0 in my Cargo.toml. The problem is that later versions of these crates upgrade the version of bytes above 0.5 while grpc-rust still uses bytes v0.5.`

source: https://github.com/stepancheg/grpc-rust/issues/190

```
error[E0308]: mismatched types
  --> /home/thomas/.cargo/registry/src/github.com-1ecc6299db9ec823/grpc-protobuf-0.8.2/src/lib.rs:27:62
   |
27 |         let mut is = CodedInputStream::from_carllerche_bytes(&buf);
   |                                                              ^^^^ expected struct `bytes::bytes::Bytes`, found struct `bytes::Bytes`
   |
   = note: expected reference `&bytes::bytes::Bytes`
              found reference `&bytes::Bytes`
   = note: perhaps two different versions of crate `bytes` are being used?

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
error: could not compile `grpc-protobuf`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by jleni** [comment]
I can confirm, something broke in the last ten days

![image](https://user-images.githubusercontent.com/13698520/104291607-04708580-54bc-11eb-93bf-edcf674a2b68.png)

**Comment by shufps** [comment]
easy fix - just remove the zemu transport - I did this in my fork and it works perfectly now :trollface:

**Comment by jleni** [comment]
That's what the 0.8.0 release does :)

**Comment by jleni** [comment]
However, I tried looking at a long term fix and the `bytes` crate has resulted in a LOT of issues upstream and it is not limited to a single crate. At this precise moment, we don't strongly rely con zemu transport in the case of rust, so yes. We just dropped support in 0.8.0 and we will reactivate once the problem gets solved.

**Comment by shufps** [comment]
perhaps I should polish my PR for Speculos transport (that doesn't need the Bytes crate) then^^

**Comment by becominginsane** [comment]
I was not able to reproduce the issue anymore checking out either b8b27b9 (in build failure screenshot in CircleCI) nor 4ea2f44 (when the version numbers were set to 0.7.0)....
If anyone is able to reproduce the problem please reopen the issue and provide steps so we can issue a new release on crates.io with the fix (if it's still needed)
