### ISSUE TITLE
Example of command with non-empty data

### ISSUE THREAD

**Issue by ndcroos** [Zondax/ledger-rs#69]
How can one send a command with non-empty data?

For example, this is a command:
```
let command = APDUCommand {
        cla: 0xe0,
        ins: 0x01,
        p1: 0x00,
        p2: 0x00,
        data: Vec::new(),
};
```
How to add data to send with the field `data`?

**Comment by becominginsane** [comment]
Each app's commands can differ but to add some data to the command simply put it in the `data` field. 
The example displays an empty `data` field, with a new empty `Vec`.
An example of how you could put some bytes in the command's data:
```
let command = APDUCommand {
    cla: 0xE0,
    ins: 0x01,
    p1: 0,
    p2: 0,
    data: vec![0xDE, 0xAD, 0xBE, 0xEF]
};
```
